### ISSUE TITLE
Getting issue while try proxy with password,

### ISSUE THREAD

**Issue by saurabhsharmaj** [serjs/socks5-server#15]
<pre>[root@master-node commands]# docker run -d --restart=always -p 1080:1080 -e PROXY_USER=root -e PROXY_PASSWORD=root serjs/go-socks5-proxy --name socks5^C
[root@master-node commands]# curl --socks5 --user root:root 192.168.0.109:1080 http://ifcfg.co
curl: (3) Port number ended with &apos;r&apos;
curl: (6) Could not resolve host: --user
curl: (6) Could not resolve host: --user
[root@master-node commands]#</pre>

**Comment by serjs** [comment]
Hi, @saurabhsharmaj!

Looks like I'am totally forgot how to use curl args for proxy user pass values :)

Already add and fix commands for docker run and plain curl commands inside [Readme.md](https://github.com/serjs/socks5-server/blob/master/README.md)

Check out with using plain curl command or inside docker container.

I suggest you to use docker example, because you can have different version of curl, where args can be differ too.

**Comment by dedpnd** [comment]
Hi, @saurabhsharmaj 
Please fix it here https://hub.docker.com/r/serjs/go-socks5-proxy/

**Comment by serjs** [comment]
I hope, updated curl args and and example inside container can fix this problem for now and near future
